version: "3"

services:
  php:
    container_name: ${APP_NAME}-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    user: www-data
    links:
      - mysql
      - memcached
    volumes:
      - ".:/var/www"
    env_file:
      - ${ENV_FILE_DIR}
  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ".:/var/www"
    env_file:
      - ${ENV_FILE_DIR}
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./.data/db/mysql:/var/lib/mysql"
    env_file:
      - ${ENV_FILE_DIR}
  memcached:
    container_name: ${APP_NAME}-memcached
    image: memcached:latest
    ports:
        - "11211:11211"
